import type { Team, Player, PitcherStats, Game, OddsData, Projection, BettingEdge } from "./types"

// Mock Teams
export const teams: Team[] = [
  { id: "nyy", name: "Yankees", abbreviation: "NYY", city: "New York", division: "AL East", league: "AL" },
  { id: "bos", name: "Red Sox", abbreviation: "BOS", city: "Boston", division: "AL East", league: "AL" },
  { id: "lad", name: "Dodgers", abbreviation: "LAD", city: "Los Angeles", division: "NL West", league: "NL" },
  { id: "sf", name: "Giants", abbreviation: "SF", city: "San Francisco", division: "NL West", league: "NL" },
  { id: "atl", name: "Braves", abbreviation: "ATL", city: "Atlanta", division: "NL East", league: "NL" },
  { id: "hou", name: "Astros", abbreviation: "HOU", city: "Houston", division: "AL West", league: "AL" },
]

// Mock Players (Pitchers)
export const players: Player[] = [
  { id: "p1", name: "Gerrit Cole", teamId: "nyy", position: "SP", throwingHand: "R" },
  { id: "p2", name: "Chris Sale", teamId: "bos", position: "SP", throwingHand: "L" },
  { id: "p3", name: "Clayton Kershaw", teamId: "lad", position: "SP", throwingHand: "L" },
  { id: "p4", name: "Logan Webb", teamId: "sf", position: "SP", throwingHand: "R" },
  { id: "p5", name: "Spencer Strider", teamId: "atl", position: "SP", throwingHand: "R" },
  { id: "p6", name: "Framber Valdez", teamId: "hou", position: "SP", throwingHand: "L" },
]

// Mock Pitcher Stats
export const pitcherStats: PitcherStats[] = [
  {
    playerId: "p1",
    season: 2024,
    era: 2.87,
    whip: 1.05,
    kPer9: 11.2,
    bbPer9: 2.1,
    innings: 195,
    wins: 15,
    losses: 7,
    saves: 0,
    fip: 2.95,
    xFIP: 3.12,
    babip: 0.285,
  },
  {
    playerId: "p2",
    season: 2024,
    era: 3.15,
    whip: 1.12,
    kPer9: 10.8,
    bbPer9: 2.8,
    innings: 178,
    wins: 12,
    losses: 8,
    saves: 0,
    fip: 3.22,
    xFIP: 3.35,
    babip: 0.295,
  },
  {
    playerId: "p3",
    season: 2024,
    era: 3.45,
    whip: 1.18,
    kPer9: 9.5,
    bbPer9: 1.9,
    innings: 165,
    wins: 11,
    losses: 9,
    saves: 0,
    fip: 3.55,
    xFIP: 3.68,
    babip: 0.302,
  },
  {
    playerId: "p4",
    season: 2024,
    era: 2.95,
    whip: 1.08,
    kPer9: 8.9,
    bbPer9: 2.3,
    innings: 188,
    wins: 14,
    losses: 6,
    saves: 0,
    fip: 3.08,
    xFIP: 3.25,
    babip: 0.288,
  },
  {
    playerId: "p5",
    season: 2024,
    era: 2.65,
    whip: 0.98,
    kPer9: 13.1,
    bbPer9: 2.5,
    innings: 172,
    wins: 16,
    losses: 5,
    saves: 0,
    fip: 2.72,
    xFIP: 2.88,
    babip: 0.275,
  },
  {
    playerId: "p6",
    season: 2024,
    era: 3.25,
    whip: 1.15,
    kPer9: 8.2,
    bbPer9: 3.1,
    innings: 192,
    wins: 13,
    losses: 8,
    saves: 0,
    fip: 3.38,
    xFIP: 3.52,
    babip: 0.298,
  },
]

// Mock Games
export const games: Game[] = [
  {
    id: "g1",
    date: new Date("2024-06-15T19:05:00"),
    homeTeamId: "nyy",
    awayTeamId: "bos",
    homeStarterId: "p1",
    awayStarterId: "p2",
    venue: "Yankee Stadium",
    weather: { temp: 78, windSpeed: 8, windDirection: "SW", conditions: "Clear" },
    status: "scheduled",
  },
  {
    id: "g2",
    date: new Date("2024-06-15T22:10:00"),
    homeTeamId: "lad",
    awayTeamId: "sf",
    homeStarterId: "p3",
    awayStarterId: "p4",
    venue: "Dodger Stadium",
    weather: { temp: 72, windSpeed: 5, windDirection: "W", conditions: "Clear" },
    status: "scheduled",
  },
  {
    id: "g3",
    date: new Date("2024-06-15T19:20:00"),
    homeTeamId: "atl",
    awayTeamId: "hou",
    homeStarterId: "p5",
    awayStarterId: "p6",
    venue: "Truist Park",
    weather: { temp: 85, windSpeed: 12, windDirection: "S", conditions: "Partly Cloudy" },
    status: "scheduled",
  },
]

// Mock Odds Data
export const oddsData: OddsData[] = [
  {
    gameId: "g1",
    bookmaker: "DraftKings",
    timestamp: new Date(),
    moneylineHome: -145,
    moneylineAway: +125,
    spreadHome: -1.5,
    spreadHomeOdds: +135,
    spreadAway: +1.5,
    spreadAwayOdds: -155,
    totalOver: 8.5,
    totalOverOdds: -110,
    totalUnder: 8.5,
    totalUnderOdds: -110,
  },
  {
    gameId: "g2",
    bookmaker: "DraftKings",
    timestamp: new Date(),
    moneylineHome: -165,
    moneylineAway: +140,
    spreadHome: -1.5,
    spreadHomeOdds: +125,
    spreadAway: +1.5,
    spreadAwayOdds: -145,
    totalOver: 7.5,
    totalOverOdds: -115,
    totalUnder: 7.5,
    totalUnderOdds: -105,
  },
  {
    gameId: "g3",
    bookmaker: "DraftKings",
    timestamp: new Date(),
    moneylineHome: -175,
    moneylineAway: +150,
    spreadHome: -1.5,
    spreadHomeOdds: +115,
    spreadAway: +1.5,
    spreadAwayOdds: -135,
    totalOver: 8.0,
    totalOverOdds: -110,
    totalUnder: 8.0,
    totalUnderOdds: -110,
  },
]

// Mock Projections
export const projections: Projection[] = [
  {
    gameId: "g1",
    model: "Composite",
    homeWinProb: 0.58,
    awayWinProb: 0.42,
    projectedHomeScore: 4.8,
    projectedAwayScore: 4.1,
    projectedTotal: 8.9,
    confidence: 0.72,
    factors: {
      pitcherMatchup: 0.85,
      recentForm: 0.78,
      homeAdvantage: 0.62,
      restDays: 0.9,
      weather: 0.55,
      bullpenStrength: 0.68,
    },
  },
  {
    gameId: "g2",
    model: "Composite",
    homeWinProb: 0.62,
    awayWinProb: 0.38,
    projectedHomeScore: 4.5,
    projectedAwayScore: 3.6,
    projectedTotal: 8.1,
    confidence: 0.68,
    factors: {
      pitcherMatchup: 0.72,
      recentForm: 0.82,
      homeAdvantage: 0.65,
      restDays: 0.88,
      weather: 0.6,
      bullpenStrength: 0.75,
    },
  },
  {
    gameId: "g3",
    model: "Composite",
    homeWinProb: 0.65,
    awayWinProb: 0.35,
    projectedHomeScore: 5.2,
    projectedAwayScore: 3.8,
    projectedTotal: 9.0,
    confidence: 0.75,
    factors: {
      pitcherMatchup: 0.88,
      recentForm: 0.85,
      homeAdvantage: 0.68,
      restDays: 0.92,
      weather: 0.48,
      bullpenStrength: 0.8,
    },
  },
]

// Mock Betting Edges
export const bettingEdges: BettingEdge[] = [
  {
    gameId: "g1",
    betType: "moneyline",
    side: "BOS",
    fairOdds: +105,
    marketOdds: +125,
    edgePercent: 4.2,
    expectedValue: 0.042,
    confidence: 0.72,
    kellyFraction: 0.021,
    recommendedUnits: 2.1,
  },
  {
    gameId: "g2",
    betType: "total",
    side: "Under 7.5",
    fairOdds: -125,
    marketOdds: -105,
    edgePercent: 3.8,
    expectedValue: 0.038,
    confidence: 0.68,
    kellyFraction: 0.019,
    recommendedUnits: 1.9,
  },
  {
    gameId: "g3",
    betType: "spread",
    side: "ATL -1.5",
    fairOdds: +105,
    marketOdds: +115,
    edgePercent: 2.5,
    expectedValue: 0.025,
    confidence: 0.75,
    kellyFraction: 0.0125,
    recommendedUnits: 1.25,
  },
]
