/**
 * Mock data for NRFI/YRFI Prediction Engine
 * All statistics are representative of the 2026 MLB season.
 */

import type { Team, Pitcher, Game, HistoricalResult, ModelAccuracy } from "./types"

// ─── Teams ────────────────────────────────────────────────────────────────────

export const teams: Team[] = [
  {
    id: "pit",
    name: "Pirates",
    abbreviation: "PIT",
    city: "Pittsburgh",
    league: "NL",
    division: "Central",
    primaryColor: "#FDB827",
    firstInning: {
      runsPerGame: 0.36,
      offenseFactor: 0.82,
      ops: 0.655,
      woba: 0.285,
      kRate: 0.238,
      bbRate: 0.072,
      yrfiRate: 0.28,
      homeYrfiRate: 0.30,
      awayYrfiRate: 0.26,
      last10YrfiRate: 0.30,
      avgRunsVsRHP: 0.34,
      avgRunsVsLHP: 0.40,
    },
  },
  {
    id: "mia",
    name: "Marlins",
    abbreviation: "MIA",
    city: "Miami",
    league: "NL",
    division: "East",
    primaryColor: "#00A3E0",
    firstInning: {
      runsPerGame: 0.37,
      offenseFactor: 0.85,
      ops: 0.672,
      woba: 0.290,
      kRate: 0.245,
      bbRate: 0.068,
      yrfiRate: 0.31,
      homeYrfiRate: 0.33,
      awayYrfiRate: 0.29,
      last10YrfiRate: 0.30,
      avgRunsVsRHP: 0.36,
      avgRunsVsLHP: 0.39,
    },
  },
  {
    id: "sf",
    name: "Giants",
    abbreviation: "SF",
    city: "San Francisco",
    league: "NL",
    division: "West",
    primaryColor: "#FD5A1E",
    firstInning: {
      runsPerGame: 0.39,
      offenseFactor: 0.90,
      ops: 0.695,
      woba: 0.302,
      kRate: 0.228,
      bbRate: 0.082,
      yrfiRate: 0.33,
      homeYrfiRate: 0.35,
      awayYrfiRate: 0.31,
      last10YrfiRate: 0.40,
      avgRunsVsRHP: 0.38,
      avgRunsVsLHP: 0.42,
    },
  },
  {
    id: "sd",
    name: "Padres",
    abbreviation: "SD",
    city: "San Diego",
    league: "NL",
    division: "West",
    primaryColor: "#2F241D",
    firstInning: {
      runsPerGame: 0.41,
      offenseFactor: 0.95,
      ops: 0.712,
      woba: 0.312,
      kRate: 0.235,
      bbRate: 0.075,
      yrfiRate: 0.35,
      homeYrfiRate: 0.36,
      awayYrfiRate: 0.34,
      last10YrfiRate: 0.30,
      avgRunsVsRHP: 0.40,
      avgRunsVsLHP: 0.43,
    },
  },
  {
    id: "min",
    name: "Twins",
    abbreviation: "MIN",
    city: "Minnesota",
    league: "AL",
    division: "Central",
    primaryColor: "#002B5C",
    firstInning: {
      runsPerGame: 0.44,
      offenseFactor: 1.02,
      ops: 0.732,
      woba: 0.322,
      kRate: 0.220,
      bbRate: 0.088,
      yrfiRate: 0.40,
      homeYrfiRate: 0.42,
      awayYrfiRate: 0.38,
      last10YrfiRate: 0.40,
      avgRunsVsRHP: 0.43,
      avgRunsVsLHP: 0.46,
    },
  },
  {
    id: "stl",
    name: "Cardinals",
    abbreviation: "STL",
    city: "St. Louis",
    league: "NL",
    division: "Central",
    primaryColor: "#C41E3A",
    firstInning: {
      runsPerGame: 0.42,
      offenseFactor: 0.98,
      ops: 0.722,
      woba: 0.318,
      kRate: 0.218,
      bbRate: 0.080,
      yrfiRate: 0.38,
      homeYrfiRate: 0.40,
      awayYrfiRate: 0.36,
      last10YrfiRate: 0.40,
      avgRunsVsRHP: 0.41,
      avgRunsVsLHP: 0.44,
    },
  },
  {
    id: "phi",
    name: "Phillies",
    abbreviation: "PHI",
    city: "Philadelphia",
    league: "NL",
    division: "East",
    primaryColor: "#E81828",
    firstInning: {
      runsPerGame: 0.48,
      offenseFactor: 1.10,
      ops: 0.758,
      woba: 0.338,
      kRate: 0.212,
      bbRate: 0.092,
      yrfiRate: 0.44,
      homeYrfiRate: 0.46,
      awayYrfiRate: 0.42,
      last10YrfiRate: 0.50,
      avgRunsVsRHP: 0.47,
      avgRunsVsLHP: 0.50,
    },
  },
  {
    id: "nyy",
    name: "Yankees",
    abbreviation: "NYY",
    city: "New York",
    league: "AL",
    division: "East",
    primaryColor: "#003087",
    firstInning: {
      runsPerGame: 0.49,
      offenseFactor: 1.12,
      ops: 0.762,
      woba: 0.340,
      kRate: 0.208,
      bbRate: 0.095,
      yrfiRate: 0.44,
      homeYrfiRate: 0.46,
      awayYrfiRate: 0.42,
      last10YrfiRate: 0.40,
      avgRunsVsRHP: 0.48,
      avgRunsVsLHP: 0.52,
    },
  },
  {
    id: "atl",
    name: "Braves",
    abbreviation: "ATL",
    city: "Atlanta",
    league: "NL",
    division: "East",
    primaryColor: "#CE1141",
    firstInning: {
      runsPerGame: 0.51,
      offenseFactor: 1.18,
      ops: 0.778,
      woba: 0.350,
      kRate: 0.218,
      bbRate: 0.098,
      yrfiRate: 0.47,
      homeYrfiRate: 0.50,
      awayYrfiRate: 0.44,
      last10YrfiRate: 0.50,
      avgRunsVsRHP: 0.50,
      avgRunsVsLHP: 0.53,
    },
  },
  {
    id: "chc",
    name: "Cubs",
    abbreviation: "CHC",
    city: "Chicago",
    league: "NL",
    division: "Central",
    primaryColor: "#0E3386",
    firstInning: {
      runsPerGame: 0.43,
      offenseFactor: 0.98,
      ops: 0.725,
      woba: 0.318,
      kRate: 0.228,
      bbRate: 0.082,
      yrfiRate: 0.38,
      homeYrfiRate: 0.40,
      awayYrfiRate: 0.36,
      last10YrfiRate: 0.40,
      avgRunsVsRHP: 0.42,
      avgRunsVsLHP: 0.45,
    },
  },
  {
    id: "hou",
    name: "Astros",
    abbreviation: "HOU",
    city: "Houston",
    league: "AL",
    division: "West",
    primaryColor: "#EB6E1F",
    firstInning: {
      runsPerGame: 0.46,
      offenseFactor: 1.05,
      ops: 0.742,
      woba: 0.328,
      kRate: 0.215,
      bbRate: 0.090,
      yrfiRate: 0.41,
      homeYrfiRate: 0.43,
      awayYrfiRate: 0.39,
      last10YrfiRate: 0.50,
      avgRunsVsRHP: 0.45,
      avgRunsVsLHP: 0.48,
    },
  },
  {
    id: "tex",
    name: "Rangers",
    abbreviation: "TEX",
    city: "Texas",
    league: "AL",
    division: "West",
    primaryColor: "#003278",
    firstInning: {
      runsPerGame: 0.47,
      offenseFactor: 1.08,
      ops: 0.750,
      woba: 0.332,
      kRate: 0.225,
      bbRate: 0.086,
      yrfiRate: 0.42,
      homeYrfiRate: 0.44,
      awayYrfiRate: 0.40,
      last10YrfiRate: 0.40,
      avgRunsVsRHP: 0.46,
      avgRunsVsLHP: 0.50,
    },
  },
]

// ─── Pitchers ─────────────────────────────────────────────────────────────────

export const pitchers: Pitcher[] = [
  {
    id: "skenes",
    name: "Paul Skenes",
    teamId: "pit",
    throws: "R",
    age: 23,
    firstInning: {
      era: 1.62,
      whip: 0.72,
      kRate: 0.335,
      bbRate: 0.052,
      hrPer9: 0.3,
      babip: 0.268,
      nrfiRate: 0.78,
      avgRunsAllowed: 0.26,
      firstBatterOBP: 0.232,
      last5Results: [true, true, true, false, true],
      last5RunsAllowed: [0, 0, 0, 1, 0],
      startCount: 24,
      homeNrfiRate: 0.80,
      awayNrfiRate: 0.76,
    },
    overall: { era: 1.98, fip: 2.15, xfip: 2.28, whip: 0.82, kPer9: 12.1, bbPer9: 2.0, innings: 142, wins: 14, losses: 4 },
  },
  {
    id: "alcantara",
    name: "Sandy Alcantara",
    teamId: "mia",
    throws: "R",
    age: 29,
    firstInning: {
      era: 2.08,
      whip: 0.88,
      kRate: 0.228,
      bbRate: 0.058,
      hrPer9: 0.5,
      babip: 0.275,
      nrfiRate: 0.74,
      avgRunsAllowed: 0.30,
      firstBatterOBP: 0.258,
      last5Results: [true, false, true, true, true],
      last5RunsAllowed: [0, 2, 0, 0, 0],
      startCount: 22,
      homeNrfiRate: 0.76,
      awayNrfiRate: 0.72,
    },
    overall: { era: 2.68, fip: 2.88, xfip: 3.02, whip: 1.02, kPer9: 8.8, bbPer9: 2.2, innings: 148, wins: 10, losses: 7 },
  },
  {
    id: "webb",
    name: "Logan Webb",
    teamId: "sf",
    throws: "R",
    age: 28,
    firstInning: {
      era: 2.32,
      whip: 0.94,
      kRate: 0.195,
      bbRate: 0.065,
      hrPer9: 0.4,
      babip: 0.268,
      nrfiRate: 0.73,
      avgRunsAllowed: 0.31,
      firstBatterOBP: 0.268,
      last5Results: [true, true, false, true, true],
      last5RunsAllowed: [0, 0, 1, 0, 0],
      startCount: 21,
      homeNrfiRate: 0.76,
      awayNrfiRate: 0.70,
    },
    overall: { era: 3.02, fip: 3.18, xfip: 3.25, whip: 1.08, kPer9: 7.5, bbPer9: 2.5, innings: 155, wins: 12, losses: 8 },
  },
  {
    id: "cease",
    name: "Dylan Cease",
    teamId: "sd",
    throws: "R",
    age: 29,
    firstInning: {
      era: 2.65,
      whip: 1.02,
      kRate: 0.275,
      bbRate: 0.088,
      hrPer9: 0.6,
      babip: 0.278,
      nrfiRate: 0.71,
      avgRunsAllowed: 0.33,
      firstBatterOBP: 0.275,
      last5Results: [false, true, true, true, false],
      last5RunsAllowed: [2, 0, 0, 0, 1],
      startCount: 20,
      homeNrfiRate: 0.73,
      awayNrfiRate: 0.69,
    },
    overall: { era: 3.22, fip: 3.35, xfip: 3.42, whip: 1.14, kPer9: 10.2, bbPer9: 3.2, innings: 138, wins: 11, losses: 7 },
  },
  {
    id: "lopez",
    name: "Pablo López",
    teamId: "min",
    throws: "R",
    age: 29,
    firstInning: {
      era: 2.88,
      whip: 1.06,
      kRate: 0.248,
      bbRate: 0.072,
      hrPer9: 0.7,
      babip: 0.282,
      nrfiRate: 0.69,
      avgRunsAllowed: 0.35,
      firstBatterOBP: 0.285,
      last5Results: [true, true, false, true, false],
      last5RunsAllowed: [0, 0, 1, 0, 2],
      startCount: 19,
      homeNrfiRate: 0.71,
      awayNrfiRate: 0.67,
    },
    overall: { era: 3.38, fip: 3.55, xfip: 3.68, whip: 1.16, kPer9: 9.2, bbPer9: 2.8, innings: 138, wins: 10, losses: 8 },
  },
  {
    id: "gray",
    name: "Sonny Gray",
    teamId: "stl",
    throws: "R",
    age: 35,
    firstInning: {
      era: 2.98,
      whip: 1.10,
      kRate: 0.228,
      bbRate: 0.082,
      hrPer9: 0.8,
      babip: 0.288,
      nrfiRate: 0.68,
      avgRunsAllowed: 0.37,
      firstBatterOBP: 0.292,
      last5Results: [true, false, true, true, false],
      last5RunsAllowed: [0, 1, 0, 0, 2],
      startCount: 20,
      homeNrfiRate: 0.70,
      awayNrfiRate: 0.66,
    },
    overall: { era: 3.52, fip: 3.65, xfip: 3.78, whip: 1.18, kPer9: 8.5, bbPer9: 3.1, innings: 132, wins: 9, losses: 8 },
  },
  {
    id: "wheeler",
    name: "Zack Wheeler",
    teamId: "phi",
    throws: "R",
    age: 35,
    firstInning: {
      era: 2.35,
      whip: 0.92,
      kRate: 0.278,
      bbRate: 0.058,
      hrPer9: 0.5,
      babip: 0.270,
      nrfiRate: 0.73,
      avgRunsAllowed: 0.31,
      firstBatterOBP: 0.248,
      last5Results: [true, true, true, false, true],
      last5RunsAllowed: [0, 0, 0, 1, 0],
      startCount: 22,
      homeNrfiRate: 0.74,
      awayNrfiRate: 0.72,
    },
    overall: { era: 2.98, fip: 3.08, xfip: 3.18, whip: 1.05, kPer9: 10.2, bbPer9: 2.2, innings: 148, wins: 13, losses: 6 },
  },
  {
    id: "cole",
    name: "Gerrit Cole",
    teamId: "nyy",
    throws: "R",
    age: 34,
    firstInning: {
      era: 2.42,
      whip: 0.96,
      kRate: 0.295,
      bbRate: 0.062,
      hrPer9: 0.6,
      babip: 0.272,
      nrfiRate: 0.72,
      avgRunsAllowed: 0.32,
      firstBatterOBP: 0.255,
      last5Results: [true, false, true, true, true],
      last5RunsAllowed: [0, 2, 0, 0, 0],
      startCount: 21,
      homeNrfiRate: 0.74,
      awayNrfiRate: 0.70,
    },
    overall: { era: 3.08, fip: 3.18, xfip: 3.28, whip: 1.08, kPer9: 11.0, bbPer9: 2.4, innings: 145, wins: 12, losses: 7 },
  },
  {
    id: "strider",
    name: "Spencer Strider",
    teamId: "atl",
    throws: "R",
    age: 26,
    firstInning: {
      era: 2.01,
      whip: 0.82,
      kRate: 0.348,
      bbRate: 0.052,
      hrPer9: 0.4,
      babip: 0.265,
      nrfiRate: 0.76,
      avgRunsAllowed: 0.28,
      firstBatterOBP: 0.228,
      last5Results: [true, true, false, true, true],
      last5RunsAllowed: [0, 0, 1, 0, 0],
      startCount: 23,
      homeNrfiRate: 0.78,
      awayNrfiRate: 0.74,
    },
    overall: { era: 2.42, fip: 2.55, xfip: 2.68, whip: 0.92, kPer9: 13.2, bbPer9: 2.0, innings: 155, wins: 15, losses: 5 },
  },
  {
    id: "stroman",
    name: "Marcus Stroman",
    teamId: "chc",
    throws: "R",
    age: 34,
    firstInning: {
      era: 3.42,
      whip: 1.22,
      kRate: 0.175,
      bbRate: 0.082,
      hrPer9: 0.5,
      babip: 0.298,
      nrfiRate: 0.63,
      avgRunsAllowed: 0.43,
      firstBatterOBP: 0.318,
      last5Results: [false, true, false, true, true],
      last5RunsAllowed: [1, 0, 2, 0, 0],
      startCount: 18,
      homeNrfiRate: 0.65,
      awayNrfiRate: 0.61,
    },
    overall: { era: 3.88, fip: 3.95, xfip: 4.02, whip: 1.28, kPer9: 6.5, bbPer9: 3.1, innings: 128, wins: 8, losses: 9 },
  },
  {
    id: "valdez",
    name: "Framber Valdez",
    teamId: "hou",
    throws: "L",
    age: 31,
    firstInning: {
      era: 2.92,
      whip: 1.12,
      kRate: 0.215,
      bbRate: 0.078,
      hrPer9: 0.3,
      babip: 0.285,
      nrfiRate: 0.68,
      avgRunsAllowed: 0.36,
      firstBatterOBP: 0.298,
      last5Results: [true, true, false, false, true],
      last5RunsAllowed: [0, 0, 1, 2, 0],
      startCount: 20,
      homeNrfiRate: 0.70,
      awayNrfiRate: 0.66,
    },
    overall: { era: 3.28, fip: 3.42, xfip: 3.55, whip: 1.18, kPer9: 8.0, bbPer9: 2.9, innings: 140, wins: 11, losses: 7 },
  },
  {
    id: "eovaldi",
    name: "Nathan Eovaldi",
    teamId: "tex",
    throws: "R",
    age: 35,
    firstInning: {
      era: 3.65,
      whip: 1.28,
      kRate: 0.202,
      bbRate: 0.088,
      hrPer9: 1.0,
      babip: 0.295,
      nrfiRate: 0.62,
      avgRunsAllowed: 0.44,
      firstBatterOBP: 0.325,
      last5Results: [true, false, false, true, false],
      last5RunsAllowed: [0, 2, 1, 0, 2],
      startCount: 17,
      homeNrfiRate: 0.63,
      awayNrfiRate: 0.61,
    },
    overall: { era: 4.02, fip: 4.15, xfip: 4.28, whip: 1.32, kPer9: 7.5, bbPer9: 3.3, innings: 115, wins: 7, losses: 9 },
  },
]

// ─── Today's Games ────────────────────────────────────────────────────────────

export const todayGames: Game[] = [
  {
    id: "g1",
    date: "2026-04-04",
    time: "1:10 PM",
    timeZone: "ET",
    homeTeamId: "mia",
    awayTeamId: "pit",
    homePitcherId: "alcantara",
    awayPitcherId: "skenes",
    venue: "loanDepot Park",
    parkFactor: 0.88,
    weather: { temperature: 82, windSpeed: 0, windDirection: "calm", conditions: "dome", humidity: 72 },
    odds: { nrfiOdds: -178, yrfiOdds: 150, bookmaker: "DraftKings" },
  },
  {
    id: "g2",
    date: "2026-04-04",
    time: "4:05 PM",
    timeZone: "ET",
    homeTeamId: "sd",
    awayTeamId: "sf",
    homePitcherId: "cease",
    awayPitcherId: "webb",
    venue: "Petco Park",
    parkFactor: 0.91,
    weather: { temperature: 68, windSpeed: 6, windDirection: "crosswind", conditions: "clear", humidity: 55 },
    odds: { nrfiOdds: -130, yrfiOdds: 110, bookmaker: "FanDuel" },
  },
  {
    id: "g3",
    date: "2026-04-04",
    time: "2:15 PM",
    timeZone: "ET",
    homeTeamId: "stl",
    awayTeamId: "min",
    homePitcherId: "gray",
    awayPitcherId: "lopez",
    venue: "Busch Stadium",
    parkFactor: 0.96,
    weather: { temperature: 65, windSpeed: 7, windDirection: "crosswind", conditions: "cloudy", humidity: 60 },
    odds: { nrfiOdds: -108, yrfiOdds: -112, bookmaker: "BetMGM" },
  },
  {
    id: "g4",
    date: "2026-04-04",
    time: "7:05 PM",
    timeZone: "ET",
    homeTeamId: "nyy",
    awayTeamId: "phi",
    homePitcherId: "cole",
    awayPitcherId: "wheeler",
    venue: "Yankee Stadium",
    parkFactor: 1.05,
    weather: { temperature: 58, windSpeed: 14, windDirection: "out", conditions: "clear", humidity: 48 },
    odds: { nrfiOdds: +102, yrfiOdds: -122, bookmaker: "Caesars" },
  },
  {
    id: "g5",
    date: "2026-04-04",
    time: "7:20 PM",
    timeZone: "ET",
    homeTeamId: "chc",
    awayTeamId: "atl",
    homePitcherId: "stroman",
    awayPitcherId: "strider",
    venue: "Wrigley Field",
    parkFactor: 1.06,
    weather: { temperature: 72, windSpeed: 11, windDirection: "out", conditions: "cloudy", humidity: 58 },
    odds: { nrfiOdds: +118, yrfiOdds: -138, bookmaker: "DraftKings" },
  },
  {
    id: "g6",
    date: "2026-04-04",
    time: "8:05 PM",
    timeZone: "ET",
    homeTeamId: "tex",
    awayTeamId: "hou",
    homePitcherId: "eovaldi",
    awayPitcherId: "valdez",
    venue: "Globe Life Field",
    parkFactor: 1.10,
    weather: { temperature: 89, windSpeed: 8, windDirection: "out", conditions: "clear", humidity: 42 },
    odds: { nrfiOdds: +148, yrfiOdds: -168, bookmaker: "BetMGM" },
  },
]

// ─── Historical Results ───────────────────────────────────────────────────────

export const historicalResults: HistoricalResult[] = [
  {
    id: "h001",
    date: "2026-04-03",
    homeTeam: "NYY",
    awayTeam: "BOS",
    homePitcher: "Gerrit Cole",
    awayPitcher: "Brayan Bello",
    venue: "Yankee Stadium",
    nrfiProbability: 0.582,
    prediction: "NRFI",
    actualResult: "NRFI",
    correct: true,
    confidence: "Medium",
    runsFirstInning: { home: 0, away: 0 },
    nrfiOdds: -128,
    yrfiOdds: 108,
    profitLoss: 0.78,
  },
  {
    id: "h002",
    date: "2026-04-03",
    homeTeam: "LAD",
    awayTeam: "SF",
    homePitcher: "Tyler Glasnow",
    awayPitcher: "Logan Webb",
    venue: "Dodger Stadium",
    nrfiProbability: 0.632,
    prediction: "NRFI",
    actualResult: "NRFI",
    correct: true,
    confidence: "High",
    runsFirstInning: { home: 0, away: 0 },
    nrfiOdds: -152,
    yrfiOdds: 130,
    profitLoss: 0.66,
  },
  {
    id: "h003",
    date: "2026-04-03",
    homeTeam: "HOU",
    awayTeam: "SEA",
    homePitcher: "Framber Valdez",
    awayPitcher: "Luis Castillo",
    venue: "Minute Maid Park",
    nrfiProbability: 0.538,
    prediction: "NRFI",
    actualResult: "YRFI",
    correct: false,
    confidence: "Low",
    runsFirstInning: { home: 1, away: 0 },
    nrfiOdds: -115,
    yrfiOdds: -105,
    profitLoss: -1.0,
  },
  {
    id: "h004",
    date: "2026-04-03",
    homeTeam: "ATL",
    awayTeam: "MIA",
    homePitcher: "Spencer Strider",
    awayPitcher: "Sandy Alcantara",
    venue: "Truist Park",
    nrfiProbability: 0.598,
    prediction: "NRFI",
    actualResult: "NRFI",
    correct: true,
    confidence: "Medium",
    runsFirstInning: { home: 0, away: 0 },
    nrfiOdds: -138,
    yrfiOdds: 118,
    profitLoss: 0.72,
  },
  {
    id: "h005",
    date: "2026-04-03",
    homeTeam: "PHI",
    awayTeam: "NYM",
    homePitcher: "Zack Wheeler",
    awayPitcher: "Kodai Senga",
    venue: "Citizens Bank Park",
    nrfiProbability: 0.455,
    prediction: "YRFI",
    actualResult: "YRFI",
    correct: true,
    confidence: "Medium",
    runsFirstInning: { home: 2, away: 0 },
    nrfiOdds: +105,
    yrfiOdds: -125,
    profitLoss: 0.80,
  },
  {
    id: "h006",
    date: "2026-04-03",
    homeTeam: "CHC",
    awayTeam: "MIL",
    homePitcher: "Marcus Stroman",
    awayPitcher: "Corbin Burnes",
    venue: "Wrigley Field",
    nrfiProbability: 0.412,
    prediction: "YRFI",
    actualResult: "NRFI",
    correct: false,
    confidence: "Medium",
    runsFirstInning: { home: 0, away: 0 },
    nrfiOdds: +125,
    yrfiOdds: -145,
    profitLoss: -1.0,
  },
  {
    id: "h007",
    date: "2026-04-02",
    homeTeam: "PIT",
    awayTeam: "CIN",
    homePitcher: "Paul Skenes",
    awayPitcher: "Hunter Greene",
    venue: "PNC Park",
    nrfiProbability: 0.618,
    prediction: "NRFI",
    actualResult: "NRFI",
    correct: true,
    confidence: "High",
    runsFirstInning: { home: 0, away: 0 },
    nrfiOdds: -148,
    yrfiOdds: 128,
    profitLoss: 0.68,
  },
  {
    id: "h008",
    date: "2026-04-02",
    homeTeam: "MIN",
    awayTeam: "DET",
    homePitcher: "Pablo López",
    awayPitcher: "Tarik Skubal",
    venue: "Target Field",
    nrfiProbability: 0.558,
    prediction: "NRFI",
    actualResult: "YRFI",
    correct: false,
    confidence: "Medium",
    runsFirstInning: { home: 0, away: 1 },
    nrfiOdds: -122,
    yrfiOdds: +102,
    profitLoss: -1.0,
  },
  {
    id: "h009",
    date: "2026-04-02",
    homeTeam: "SD",
    awayTeam: "COL",
    homePitcher: "Dylan Cease",
    awayPitcher: "Cal Quantrill",
    venue: "Petco Park",
    nrfiProbability: 0.655,
    prediction: "NRFI",
    actualResult: "NRFI",
    correct: true,
    confidence: "High",
    runsFirstInning: { home: 0, away: 0 },
    nrfiOdds: -182,
    yrfiOdds: 155,
    profitLoss: 0.55,
  },
  {
    id: "h010",
    date: "2026-04-02",
    homeTeam: "TEX",
    awayTeam: "OAK",
    homePitcher: "Nathan Eovaldi",
    awayPitcher: "JP Sears",
    venue: "Globe Life Field",
    nrfiProbability: 0.382,
    prediction: "YRFI",
    actualResult: "YRFI",
    correct: true,
    confidence: "High",
    runsFirstInning: { home: 1, away: 1 },
    nrfiOdds: +148,
    yrfiOdds: -168,
    profitLoss: 0.60,
  },
  {
    id: "h011",
    date: "2026-04-01",
    homeTeam: "STL",
    awayTeam: "KC",
    homePitcher: "Sonny Gray",
    awayPitcher: "Cole Ragans",
    venue: "Busch Stadium",
    nrfiProbability: 0.522,
    prediction: "NRFI",
    actualResult: "NRFI",
    correct: true,
    confidence: "Low",
    runsFirstInning: { home: 0, away: 0 },
    nrfiOdds: -108,
    yrfiOdds: -112,
    profitLoss: 0.93,
  },
  {
    id: "h012",
    date: "2026-04-01",
    homeTeam: "MIA",
    awayTeam: "NYM",
    homePitcher: "Sandy Alcantara",
    awayPitcher: "Kodai Senga",
    venue: "loanDepot Park",
    nrfiProbability: 0.678,
    prediction: "NRFI",
    actualResult: "NRFI",
    correct: true,
    confidence: "High",
    runsFirstInning: { home: 0, away: 0 },
    nrfiOdds: -198,
    yrfiOdds: 168,
    profitLoss: 0.51,
  },
  {
    id: "h013",
    date: "2026-04-01",
    homeTeam: "ATL",
    awayTeam: "PHI",
    homePitcher: "Spencer Strider",
    awayPitcher: "Zack Wheeler",
    venue: "Truist Park",
    nrfiProbability: 0.508,
    prediction: "NRFI",
    actualResult: "YRFI",
    correct: false,
    confidence: "Low",
    runsFirstInning: { home: 1, away: 0 },
    nrfiOdds: -105,
    yrfiOdds: -115,
    profitLoss: -1.0,
  },
  {
    id: "h014",
    date: "2026-03-31",
    homeTeam: "HOU",
    awayTeam: "LAA",
    homePitcher: "Framber Valdez",
    awayPitcher: "Tyler Anderson",
    venue: "Minute Maid Park",
    nrfiProbability: 0.445,
    prediction: "YRFI",
    actualResult: "YRFI",
    correct: true,
    confidence: "Medium",
    runsFirstInning: { home: 2, away: 0 },
    nrfiOdds: +108,
    yrfiOdds: -128,
    profitLoss: 0.78,
  },
  {
    id: "h015",
    date: "2026-03-31",
    homeTeam: "NYY",
    awayTeam: "TOR",
    homePitcher: "Gerrit Cole",
    awayPitcher: "Kevin Gausman",
    venue: "Yankee Stadium",
    nrfiProbability: 0.565,
    prediction: "NRFI",
    actualResult: "NRFI",
    correct: true,
    confidence: "Medium",
    runsFirstInning: { home: 0, away: 0 },
    nrfiOdds: -122,
    yrfiOdds: +102,
    profitLoss: 0.82,
  },
  {
    id: "h016",
    date: "2026-03-31",
    homeTeam: "CHC",
    awayTeam: "STL",
    homePitcher: "Marcus Stroman",
    awayPitcher: "Sonny Gray",
    venue: "Wrigley Field",
    nrfiProbability: 0.428,
    prediction: "YRFI",
    actualResult: "YRFI",
    correct: true,
    confidence: "Medium",
    runsFirstInning: { home: 0, away: 2 },
    nrfiOdds: +118,
    yrfiOdds: -138,
    profitLoss: 0.72,
  },
  {
    id: "h017",
    date: "2026-03-30",
    homeTeam: "SF",
    awayTeam: "ARI",
    homePitcher: "Logan Webb",
    awayPitcher: "Corbin Burnes",
    venue: "Oracle Park",
    nrfiProbability: 0.642,
    prediction: "NRFI",
    actualResult: "NRFI",
    correct: true,
    confidence: "High",
    runsFirstInning: { home: 0, away: 0 },
    nrfiOdds: -165,
    yrfiOdds: 142,
    profitLoss: 0.61,
  },
  {
    id: "h018",
    date: "2026-03-30",
    homeTeam: "PIT",
    awayTeam: "MIL",
    homePitcher: "Paul Skenes",
    awayPitcher: "Freddy Peralta",
    venue: "PNC Park",
    nrfiProbability: 0.588,
    prediction: "NRFI",
    actualResult: "NRFI",
    correct: true,
    confidence: "Medium",
    runsFirstInning: { home: 0, away: 0 },
    nrfiOdds: -132,
    yrfiOdds: 112,
    profitLoss: 0.76,
  },
  {
    id: "h019",
    date: "2026-03-30",
    homeTeam: "MIN",
    awayTeam: "CWS",
    homePitcher: "Pablo López",
    awayPitcher: "Chris Flexen",
    venue: "Target Field",
    nrfiProbability: 0.352,
    prediction: "YRFI",
    actualResult: "YRFI",
    correct: true,
    confidence: "High",
    runsFirstInning: { home: 3, away: 0 },
    nrfiOdds: +162,
    yrfiOdds: -188,
    profitLoss: 0.53,
  },
  {
    id: "h020",
    date: "2026-03-29",
    homeTeam: "SD",
    awayTeam: "MIA",
    homePitcher: "Dylan Cease",
    awayPitcher: "Sandy Alcantara",
    venue: "Petco Park",
    nrfiProbability: 0.688,
    prediction: "NRFI",
    actualResult: "YRFI",
    correct: false,
    confidence: "High",
    runsFirstInning: { home: 0, away: 1 },
    nrfiOdds: -208,
    yrfiOdds: 175,
    profitLoss: -1.0,
  },
]

// ─── Model Accuracy ───────────────────────────────────────────────────────────

export const modelAccuracy: ModelAccuracy = {
  totalPredictions: 20,
  correct: 15,
  accuracy: 0.75,
  nrfiAccuracy: 0.786,
  yrfiAccuracy: 0.714,
  highConfAccuracy: 0.818,
  medConfAccuracy: 0.727,
  roi: 0.148,
  calibrationData: [
    { predictedBin: 0.35, actualRate: 1.0, count: 3 },
    { predictedBin: 0.45, actualRate: 0.75, count: 4 },
    { predictedBin: 0.55, actualRate: 0.60, count: 5 },
    { predictedBin: 0.65, actualRate: 0.71, count: 7 },
    { predictedBin: 0.70, actualRate: 0.67, count: 6 },   // one upset at 0.688
  ],
  monthlyData: [
    { month: "Mar 2026", accuracy: 0.75, predictions: 20, roi: 0.148 },
    { month: "Sep 2025", accuracy: 0.702, predictions: 124, roi: 0.092 },
    { month: "Aug 2025", accuracy: 0.718, predictions: 138, roi: 0.112 },
    { month: "Jul 2025", accuracy: 0.731, predictions: 142, roi: 0.128 },
    { month: "Jun 2025", accuracy: 0.688, predictions: 130, roi: 0.065 },
    { month: "May 2025", accuracy: 0.705, predictions: 136, roi: 0.085 },
  ],
}

// ─── Lookup Maps ──────────────────────────────────────────────────────────────

export const teamMap = new Map(teams.map((t) => [t.id, t]))
export const pitcherMap = new Map(pitchers.map((p) => [p.id, p]))
