/**
 * Mock data for NRFI/YRFI Prediction Engine
 * All statistics are representative of the 2026 MLB season.
 */

import type { Team, Pitcher, Game, HistoricalResult, ModelAccuracy } from "./types"

// ─── Teams ────────────────────────────────────────────────────────────────────

export const teams: Team[] = [
  {
    id: "pit",
    name: "Pirates",
    abbreviation: "PIT",
    city: "Pittsburgh",
    league: "NL",
    division: "Central",
    primaryColor: "#FDB827",
    firstInning: {
      runsPerGame: 0.36,
      offenseFactor: 0.82,
      ops: 0.655,
      woba: 0.285,
      kRate: 0.238,
      bbRate: 0.072,
      yrfiRate: 0.28,
      homeYrfiRate: 0.30,
      awayYrfiRate: 0.26,
      last10YrfiRate: 0.30,
      avgRunsVsRHP: 0.34,
      avgRunsVsLHP: 0.40,
    },
  },
  {
    id: "mia",
    name: "Marlins",
    abbreviation: "MIA",
    city: "Miami",
    league: "NL",
    division: "East",
    primaryColor: "#00A3E0",
    firstInning: {
      runsPerGame: 0.37,
      offenseFactor: 0.85,
      ops: 0.672,
      woba: 0.290,
      kRate: 0.245,
      bbRate: 0.068,
      yrfiRate: 0.31,
      homeYrfiRate: 0.33,
      awayYrfiRate: 0.29,
      last10YrfiRate: 0.30,
      avgRunsVsRHP: 0.36,
      avgRunsVsLHP: 0.39,
    },
  },
  {
    id: "sf",
    name: "Giants",
    abbreviation: "SF",
    city: "San Francisco",
    league: "NL",
    division: "West",
    primaryColor: "#FD5A1E",
    firstInning: {
      runsPerGame: 0.39,
      offenseFactor: 0.90,
      ops: 0.695,
      woba: 0.302,
      kRate: 0.228,
      bbRate: 0.082,
      yrfiRate: 0.33,
      homeYrfiRate: 0.35,
      awayYrfiRate: 0.31,
      last10YrfiRate: 0.40,
      avgRunsVsRHP: 0.38,
      avgRunsVsLHP: 0.42,
    },
  },
  {
    id: "sd",
    name: "Padres",
    abbreviation: "SD",
    city: "San Diego",
    league: "NL",
    division: "West",
    primaryColor: "#2F241D",
    firstInning: {
      runsPerGame: 0.41,
      offenseFactor: 0.95,
      ops: 0.712,
      woba: 0.312,
      kRate: 0.235,
      bbRate: 0.075,
      yrfiRate: 0.35,
      homeYrfiRate: 0.36,
      awayYrfiRate: 0.34,
      last10YrfiRate: 0.30,
      avgRunsVsRHP: 0.40,
      avgRunsVsLHP: 0.43,
    },
  },
  {
    id: "min",
    name: "Twins",
    abbreviation: "MIN",
    city: "Minnesota",
    league: "AL",
    division: "Central",
    primaryColor: "#002B5C",
    firstInning: {
      runsPerGame: 0.44,
      offenseFactor: 1.02,
      ops: 0.732,
      woba: 0.322,
      kRate: 0.220,
      bbRate: 0.088,
      yrfiRate: 0.40,
      homeYrfiRate: 0.42,
      awayYrfiRate: 0.38,
      last10YrfiRate: 0.40,
      avgRunsVsRHP: 0.43,
      avgRunsVsLHP: 0.46,
    },
  },
  {
    id: "stl",
    name: "Cardinals",
    abbreviation: "STL",
    city: "St. Louis",
    league: "NL",
    division: "Central",
    primaryColor: "#C41E3A",
    firstInning: {
      runsPerGame: 0.42,
      offenseFactor: 0.98,
      ops: 0.722,
      woba: 0.318,
      kRate: 0.218,
      bbRate: 0.080,
      yrfiRate: 0.38,
      homeYrfiRate: 0.40,
      awayYrfiRate: 0.36,
      last10YrfiRate: 0.40,
      avgRunsVsRHP: 0.41,
      avgRunsVsLHP: 0.44,
    },
  },
  {
    id: "phi",
    name: "Phillies",
    abbreviation: "PHI",
    city: "Philadelphia",
    league: "NL",
    division: "East",
    primaryColor: "#E81828",
    firstInning: {
      runsPerGame: 0.48,
      offenseFactor: 1.10,
      ops: 0.758,
      woba: 0.338,
      kRate: 0.212,
      bbRate: 0.092,
      yrfiRate: 0.44,
      homeYrfiRate: 0.46,
      awayYrfiRate: 0.42,
      last10YrfiRate: 0.50,
      avgRunsVsRHP: 0.47,
      avgRunsVsLHP: 0.50,
    },
  },
  {
    id: "nyy",
    name: "Yankees",
    abbreviation: "NYY",
    city: "New York",
    league: "AL",
    division: "East",
    primaryColor: "#003087",
    firstInning: {
      runsPerGame: 0.49,
      offenseFactor: 1.12,
      ops: 0.762,
      woba: 0.340,
      kRate: 0.208,
      bbRate: 0.095,
      yrfiRate: 0.44,
      homeYrfiRate: 0.46,
      awayYrfiRate: 0.42,
      last10YrfiRate: 0.40,
      avgRunsVsRHP: 0.48,
      avgRunsVsLHP: 0.52,
    },
  },
  {
    id: "atl",
    name: "Braves",
    abbreviation: "ATL",
    city: "Atlanta",
    league: "NL",
    division: "East",
    primaryColor: "#CE1141",
    firstInning: {
      runsPerGame: 0.51,
      offenseFactor: 1.18,
      ops: 0.778,
      woba: 0.350,
      kRate: 0.218,
      bbRate: 0.098,
      yrfiRate: 0.47,
      homeYrfiRate: 0.50,
      awayYrfiRate: 0.44,
      last10YrfiRate: 0.50,
      avgRunsVsRHP: 0.50,
      avgRunsVsLHP: 0.53,
    },
  },
  {
    id: "chc",
    name: "Cubs",
    abbreviation: "CHC",
    city: "Chicago",
    league: "NL",
    division: "Central",
    primaryColor: "#0E3386",
    firstInning: {
      runsPerGame: 0.43,
      offenseFactor: 0.98,
      ops: 0.725,
      woba: 0.318,
      kRate: 0.228,
      bbRate: 0.082,
      yrfiRate: 0.38,
      homeYrfiRate: 0.40,
      awayYrfiRate: 0.36,
      last10YrfiRate: 0.40,
      avgRunsVsRHP: 0.42,
      avgRunsVsLHP: 0.45,
    },
  },
  {
    id: "hou",
    name: "Astros",
    abbreviation: "HOU",
    city: "Houston",
    league: "AL",
    division: "West",
    primaryColor: "#EB6E1F",
    firstInning: {
      runsPerGame: 0.46,
      offenseFactor: 1.05,
      ops: 0.742,
      woba: 0.328,
      kRate: 0.215,
      bbRate: 0.090,
      yrfiRate: 0.41,
      homeYrfiRate: 0.43,
      awayYrfiRate: 0.39,
      last10YrfiRate: 0.50,
      avgRunsVsRHP: 0.45,
      avgRunsVsLHP: 0.48,
    },
  },
  {
    id: "tex",
    name: "Rangers",
    abbreviation: "TEX",
    city: "Texas",
    league: "AL",
    division: "West",
    primaryColor: "#003278",
    firstInning: {
      runsPerGame: 0.47,
      offenseFactor: 1.08,
      ops: 0.750,
      woba: 0.332,
      kRate: 0.225,
      bbRate: 0.086,
      yrfiRate: 0.42,
      homeYrfiRate: 0.44,
      awayYrfiRate: 0.40,
      last10YrfiRate: 0.40,
      avgRunsVsRHP: 0.46,
      avgRunsVsLHP: 0.50,
    },
  },
]

// ─── Pitchers ─────────────────────────────────────────────────────────────────

export const pitchers: Pitcher[] = [
  {
    id: "skenes",
    name: "Paul Skenes",
    teamId: "pit",
    throws: "R",
    age: 23,
    firstInning: {
      era: 1.62,
      whip: 0.72,
      kRate: 0.335,
      bbRate: 0.052,
      hrPer9: 0.3,
      babip: 0.268,
      nrfiRate: 0.78,
      avgRunsAllowed: 0.26,
      firstBatterOBP: 0.232,
      last5Results: [true, true, true, false, true],
      last5RunsAllowed: [0, 0, 0, 1, 0],
      startCount: 24,
      homeNrfiRate: 0.80,
      awayNrfiRate: 0.76,
    },
    overall: { era: 1.98, fip: 2.15, xfip: 2.28, whip: 0.82, kPer9: 12.1, bbPer9: 2.0, innings: 142, wins: 14, losses: 4 },
  },
  {
    id: "alcantara",
    name: "Sandy Alcantara",
    teamId: "mia",
    throws: "R",
    age: 29,
    firstInning: {
      era: 2.08,
      whip: 0.88,
      kRate: 0.228,
      bbRate: 0.058,
      hrPer9: 0.5,
      babip: 0.275,
      nrfiRate: 0.74,
      avgRunsAllowed: 0.30,
      firstBatterOBP: 0.258,
      last5Results: [true, false, true, true, true],
      last5RunsAllowed: [0, 2, 0, 0, 0],
      startCount: 22,
      homeNrfiRate: 0.76,
      awayNrfiRate: 0.72,
    },
    overall: { era: 2.68, fip: 2.88, xfip: 3.02, whip: 1.02, kPer9: 8.8, bbPer9: 2.2, innings: 148, wins: 10, losses: 7 },
  },
  {
    id: "webb",
    name: "Logan Webb",
    teamId: "sf",
    throws: "R",
    age: 28,
    firstInning: {
      era: 2.32,
      whip: 0.94,
      kRate: 0.195,
      bbRate: 0.065,
      hrPer9: 0.4,
      babip: 0.268,
      nrfiRate: 0.73,
      avgRunsAllowed: 0.31,
      firstBatterOBP: 0.268,
      last5Results: [true, true, false, true, true],
      last5RunsAllowed: [0, 0, 1, 0, 0],
      startCount: 21,
      homeNrfiRate: 0.76,
      awayNrfiRate: 0.70,
    },
    overall: { era: 3.02, fip: 3.18, xfip: 3.25, whip: 1.08, kPer9: 7.5, bbPer9: 2.5, innings: 155, wins: 12, losses: 8 },
  },
  {
    id: "cease",
    name: "Dylan Cease",
    teamId: "sd",
    throws: "R",
    age: 29,
    firstInning: {
      era: 2.65,
      whip: 1.02,
      kRate: 0.275,
      bbRate: 0.088,
      hrPer9: 0.6,
      babip: 0.278,
      nrfiRate: 0.71,
      avgRunsAllowed: 0.33,
      firstBatterOBP: 0.275,
      last5Results: [false, true, true, true, false],
      last5RunsAllowed: [2, 0, 0, 0, 1],
      startCount: 20,
      homeNrfiRate: 0.73,
      awayNrfiRate: 0.69,
    },
    overall: { era: 3.22, fip: 3.35, xfip: 3.42, whip: 1.14, kPer9: 10.2, bbPer9: 3.2, innings: 138, wins: 11, losses: 7 },
  },
  {
    id: "lopez",
    name: "Pablo López",
    teamId: "min",
    throws: "R",
    age: 29,
    firstInning: {
      era: 2.88,
      whip: 1.06,
      kRate: 0.248,
      bbRate: 0.072,
      hrPer9: 0.7,
      babip: 0.282,
      nrfiRate: 0.69,
      avgRunsAllowed: 0.35,
      firstBatterOBP: 0.285,
      last5Results: [true, true, false, true, false],
      last5RunsAllowed: [0, 0, 1, 0, 2],
      startCount: 19,
      homeNrfiRate: 0.71,
      awayNrfiRate: 0.67,
    },
    overall: { era: 3.38, fip: 3.55, xfip: 3.68, whip: 1.16, kPer9: 9.2, bbPer9: 2.8, innings: 138, wins: 10, losses: 8 },
  },
  {
    id: "gray",
    name: "Sonny Gray",
    teamId: "stl",
    throws: "R",
    age: 35,
    firstInning: {
      era: 2.98,
      whip: 1.10,
      kRate: 0.228,
      bbRate: 0.082,
      hrPer9: 0.8,
      babip: 0.288,
      nrfiRate: 0.68,
      avgRunsAllowed: 0.37,
      firstBatterOBP: 0.292,
      last5Results: [true, false, true, true, false],
      last5RunsAllowed: [0, 1, 0, 0, 2],
      startCount: 20,
      homeNrfiRate: 0.70,
      awayNrfiRate: 0.66,
    },
    overall: { era: 3.52, fip: 3.65, xfip: 3.78, whip: 1.18, kPer9: 8.5, bbPer9: 3.1, innings: 132, wins: 9, losses: 8 },
  },
  {
    id: "wheeler",
    name: "Zack Wheeler",
    teamId: "phi",
    throws: "R",
    age: 35,
    firstInning: {
      era: 2.35,
      whip: 0.92,
      kRate: 0.278,
      bbRate: 0.058,
      hrPer9: 0.5,
      babip: 0.270,
      nrfiRate: 0.73,
      avgRunsAllowed: 0.31,
      firstBatterOBP: 0.248,
      last5Results: [true, true, true, false, true],
      last5RunsAllowed: [0, 0, 0, 1, 0],
      startCount: 22,
      homeNrfiRate: 0.74,
      awayNrfiRate: 0.72,
    },
    overall: { era: 2.98, fip: 3.08, xfip: 3.18, whip: 1.05, kPer9: 10.2, bbPer9: 2.2, innings: 148, wins: 13, losses: 6 },
  },
  {
    id: "cole",
    name: "Gerrit Cole",
    teamId: "nyy",
    throws: "R",
    age: 34,
    firstInning: {
      era: 2.42,
      whip: 0.96,
      kRate: 0.295,
      bbRate: 0.062,
      hrPer9: 0.6,
      babip: 0.272,
      nrfiRate: 0.72,
      avgRunsAllowed: 0.32,
      firstBatterOBP: 0.255,
      last5Results: [true, false, true, true, true],
      last5RunsAllowed: [0, 2, 0, 0, 0],
      startCount: 21,
      homeNrfiRate: 0.74,
      awayNrfiRate: 0.70,
    },
    overall: { era: 3.08, fip: 3.18, xfip: 3.28, whip: 1.08, kPer9: 11.0, bbPer9: 2.4, innings: 145, wins: 12, losses: 7 },
  },
  {
    id: "strider",
    name: "Spencer Strider",
    teamId: "atl",
    throws: "R",
    age: 26,
    firstInning: {
      era: 2.01,
      whip: 0.82,
      kRate: 0.348,
      bbRate: 0.052,
      hrPer9: 0.4,
      babip: 0.265,
      nrfiRate: 0.76,
      avgRunsAllowed: 0.28,
      firstBatterOBP: 0.228,
      last5Results: [true, true, false, true, true],
      last5RunsAllowed: [0, 0, 1, 0, 0],
      startCount: 23,
      homeNrfiRate: 0.78,
      awayNrfiRate: 0.74,
    },
    overall: { era: 2.42, fip: 2.55, xfip: 2.68, whip: 0.92, kPer9: 13.2, bbPer9: 2.0, innings: 155, wins: 15, losses: 5 },
  },
  {
    id: "stroman",
    name: "Marcus Stroman",
    teamId: "chc",
    throws: "R",
    age: 34,
    firstInning: {
      era: 3.42,
      whip: 1.22,
      kRate: 0.175,
      bbRate: 0.082,
      hrPer9: 0.5,
      babip: 0.298,
      nrfiRate: 0.63,
      avgRunsAllowed: 0.43,
      firstBatterOBP: 0.318,
      last5Results: [false, true, false, true, true],
      last5RunsAllowed: [1, 0, 2, 0, 0],
      startCount: 18,
      homeNrfiRate: 0.65,
      awayNrfiRate: 0.61,
    },
    overall: { era: 3.88, fip: 3.95, xfip: 4.02, whip: 1.28, kPer9: 6.5, bbPer9: 3.1, innings: 128, wins: 8, losses: 9 },
  },
  {
    id: "valdez",
    name: "Framber Valdez",
    teamId: "hou",
    throws: "L",
    age: 31,
    firstInning: {
      era: 2.92,
      whip: 1.12,
      kRate: 0.215,
      bbRate: 0.078,
      hrPer9: 0.3,
      babip: 0.285,
      nrfiRate: 0.68,
      avgRunsAllowed: 0.36,
      firstBatterOBP: 0.298,
      last5Results: [true, true, false, false, true],
      last5RunsAllowed: [0, 0, 1, 2, 0],
      startCount: 20,
      homeNrfiRate: 0.70,
      awayNrfiRate: 0.66,
    },
    overall: { era: 3.28, fip: 3.42, xfip: 3.55, whip: 1.18, kPer9: 8.0, bbPer9: 2.9, innings: 140, wins: 11, losses: 7 },
  },
  {
    id: "eovaldi",
    name: "Nathan Eovaldi",
    teamId: "tex",
    throws: "R",
    age: 35,
    firstInning: {
      era: 3.65,
      whip: 1.28,
      kRate: 0.202,
      bbRate: 0.088,
      hrPer9: 1.0,
      babip: 0.295,
      nrfiRate: 0.62,
      avgRunsAllowed: 0.44,
      firstBatterOBP: 0.325,
      last5Results: [true, false, false, true, false],
      last5RunsAllowed: [0, 2, 1, 0, 2],
      startCount: 17,
      homeNrfiRate: 0.63,
      awayNrfiRate: 0.61,
    },
    overall: { era: 4.02, fip: 4.15, xfip: 4.28, whip: 1.32, kPer9: 7.5, bbPer9: 3.3, innings: 115, wins: 7, losses: 9 },
  },
]

// ─── Today's Games ────────────────────────────────────────────────────────────

export const todayGames: Game[] = [
  {
    id: "g1",
    date: "2026-04-04",
    time: "1:10 PM",
    timeZone: "ET",
    homeTeamId: "mia",
    awayTeamId: "pit",
    homePitcherId: "alcantara",
    awayPitcherId: "skenes",
    venue: "loanDepot Park",
    parkFactor: 0.88,
    weather: { temperature: 82, windSpeed: 0, windDirection: "calm", conditions: "dome", humidity: 72 },
    odds: { nrfiOdds: -178, yrfiOdds: 150, bookmaker: "DraftKings" },
  },
  {
    id: "g2",
    date: "2026-04-04",
    time: "4:05 PM",
    timeZone: "ET",
    homeTeamId: "sd",
    awayTeamId: "sf",
    homePitcherId: "cease",
    awayPitcherId: "webb",
    venue: "Petco Park",
    parkFactor: 0.91,
    weather: { temperature: 68, windSpeed: 6, windDirection: "crosswind", conditions: "clear", humidity: 55 },
    odds: { nrfiOdds: -130, yrfiOdds: 110, bookmaker: "FanDuel" },
  },
  {
    id: "g3",
    date: "2026-04-04",
    time: "2:15 PM",
    timeZone: "ET",
    homeTeamId: "stl",
    awayTeamId: "min",
    homePitcherId: "gray",
    awayPitcherId: "lopez",
    venue: "Busch Stadium",
    parkFactor: 0.96,
    weather: { temperature: 65, windSpeed: 7, windDirection: "crosswind", conditions: "cloudy", humidity: 60 },
    odds: { nrfiOdds: -108, yrfiOdds: -112, bookmaker: "BetMGM" },
  },
  {
    id: "g4",
    date: "2026-04-04",
    time: "7:05 PM",
    timeZone: "ET",
    homeTeamId: "nyy",
    awayTeamId: "phi",
    homePitcherId: "cole",
    awayPitcherId: "wheeler",
    venue: "Yankee Stadium",
    parkFactor: 1.05,
    weather: { temperature: 58, windSpeed: 14, windDirection: "out", conditions: "clear", humidity: 48 },
    odds: { nrfiOdds: +102, yrfiOdds: -122, bookmaker: "Caesars" },
  },
  {
    id: "g5",
    date: "2026-04-04",
    time: "7:20 PM",
    timeZone: "ET",
    homeTeamId: "chc",
    awayTeamId: "atl",
    homePitcherId: "stroman",
    awayPitcherId: "strider",
    venue: "Wrigley Field",
    parkFactor: 1.06,
    weather: { temperature: 72, windSpeed: 11, windDirection: "out", conditions: "cloudy", humidity: 58 },
    odds: { nrfiOdds: +118, yrfiOdds: -138, bookmaker: "DraftKings" },
  },
  {
    id: "g6",
    date: "2026-04-04",
    time: "8:05 PM",
    timeZone: "ET",
    homeTeamId: "tex",
    awayTeamId: "hou",
    homePitcherId: "eovaldi",
    awayPitcherId: "valdez",
    venue: "Globe Life Field",
    parkFactor: 1.10,
    weather: { temperature: 89, windSpeed: 8, windDirection: "out", conditions: "clear", humidity: 42 },
    odds: { nrfiOdds: +148, yrfiOdds: -168, bookmaker: "BetMGM" },
  },
]

// ─── Historical Results ───────────────────────────────────────────────────────

// No historical predictions yet — results will be tracked once live data is active.
export const historicalResults: HistoricalResult[] = []

// ─── Model Accuracy ───────────────────────────────────────────────────────────

export const modelAccuracy: ModelAccuracy = {
  totalPredictions: 0,
  correct: 0,
  accuracy: 0,
  nrfiAccuracy: 0,
  yrfiAccuracy: 0,
  highConfAccuracy: 0,
  medConfAccuracy: 0,
  roi: 0,
  calibrationData: [],
  monthlyData: [],
}

// ─── Lookup Maps ──────────────────────────────────────────────────────────────

export const teamMap = new Map(teams.map((t) => [t.id, t]))
export const pitcherMap = new Map(pitchers.map((p) => [p.id, p]))
