/**
 * AUTO-GENERATED by scripts/data/refresh_umpires.ts — do not edit by hand.
 * Generated: 2026-06-10T19:32:45.538Z
 * Source: game_results (8285 games) + MLB boxscore officials.
 * careerNrfi is EB-shrunk toward 0.516 (k=20); zoneTightness = clamp(−zK/2, −1, 1).
 */

import type { UmpireProfile } from "./umpire-zone"

export const GENERATED_UMPIRE_PROFILES: Record<string, Readonly<UmpireProfile>> = {
  "483569": { zoneTightness: -0.2965, careerNrfi: 0.5100, sample: 112 }, // Vic Carapazza
  "427139": { zoneTightness: -0.2477, careerNrfi: 0.6071, sample: 109 }, // Doug Eddings
  "427344": { zoneTightness: -0.6051, careerNrfi: 0.5219, sample: 109 }, // Bill Miller
  "482663": { zoneTightness: -0.1394, careerNrfi: 0.5025, sample: 108 }, // David Rackley
  "483561": { zoneTightness: -0.1216, careerNrfi: 0.5773, sample: 107 }, // Lance Barrett
  "554242": { zoneTightness: -0.3616, careerNrfi: 0.4907, sample: 107 }, // Edwin Moscoso
  "605673": { zoneTightness: 0.2189, careerNrfi: 0.4787, sample: 106 }, // Alex Tosi
  "483564": { zoneTightness: 0.2127, careerNrfi: 0.5184, sample: 106 }, // Dan Bellino
  "503077": { zoneTightness: -0.1408, careerNrfi: 0.5105, sample: 106 }, // Adam Hamari
  "483919": { zoneTightness: 0.1710, careerNrfi: 0.4666, sample: 105 }, // Mark Ripperger
  "427013": { zoneTightness: 0.4773, careerNrfi: 0.4506, sample: 105 }, // Lance Barksdale
  "623949": { zoneTightness: 0.5194, careerNrfi: 0.4623, sample: 104 }, // Clint Vondrak
  "605674": { zoneTightness: -0.2242, careerNrfi: 0.5187, sample: 104 }, // Ryan Wills
  "596805": { zoneTightness: -0.0730, careerNrfi: 0.4381, sample: 104 }, // John Libka
  "608158": { zoneTightness: 0.0153, careerNrfi: 0.4784, sample: 104 }, // Nate Tomlinson
  "544728": { zoneTightness: 0.2572, careerNrfi: 0.5148, sample: 103 }, // Nic Lentz
  "547380": { zoneTightness: 0.3652, careerNrfi: 0.5311, sample: 103 }, // Carlos Torres
  "573597": { zoneTightness: 0.0476, careerNrfi: 0.5148, sample: 103 }, // Gabe Morales
  "639723": { zoneTightness: -0.0605, careerNrfi: 0.5190, sample: 102 }, // Brennan Miller
  "511890": { zoneTightness: 0.2213, careerNrfi: 0.5026, sample: 102 }, // Quinn Wolcott
  "598411": { zoneTightness: -0.3295, careerNrfi: 0.5354, sample: 102 }, // Nestor Ceja
  "427315": { zoneTightness: 0.3046, careerNrfi: 0.5436, sample: 102 }, // Alfonso Márquez
  "484198": { zoneTightness: -0.0669, careerNrfi: 0.5190, sample: 102 }, // Alan Porter
  "482666": { zoneTightness: -0.1630, careerNrfi: 0.5190, sample: 102 }, // D.J. Reyburn
  "428442": { zoneTightness: 0.3878, careerNrfi: 0.5190, sample: 102 }, // James Hoye
  "644760": { zoneTightness: 0.0163, careerNrfi: 0.5354, sample: 102 }, // Adam Beck
  "427248": { zoneTightness: 0.2021, careerNrfi: 0.5190, sample: 102 }, // Dan Iassogna
  "596740": { zoneTightness: 0.1380, careerNrfi: 0.4616, sample: 102 }, // Jansen Visconti
  "503493": { zoneTightness: -0.1252, careerNrfi: 0.5233, sample: 101 }, // Sean Barber
  "429805": { zoneTightness: 0.5335, careerNrfi: 0.5150, sample: 101 }, // Todd Tichenor
  "623946": { zoneTightness: 0.0169, careerNrfi: 0.4076, sample: 101 }, // Malachi Moore
  "483912": { zoneTightness: -0.2737, careerNrfi: 0.5150, sample: 101 }, // Mike Muchlinski
  "503490": { zoneTightness: -0.0090, careerNrfi: 0.5150, sample: 101 }, // Chris Segal
  "521889": { zoneTightness: 0.0298, careerNrfi: 0.4407, sample: 101 }, // Stu Scheurwater
  "482631": { zoneTightness: -0.6483, careerNrfi: 0.5068, sample: 101 }, // Mike Estabrook
  "594151": { zoneTightness: 0.1932, careerNrfi: 0.4777, sample: 100 }, // Ramon De Jesus
  "483630": { zoneTightness: -0.1714, careerNrfi: 0.5277, sample: 100 }, // John Tumpane
  "605670": { zoneTightness: 0.2844, careerNrfi: 0.5443, sample: 100 }, // Dan Merzel
  "427164": { zoneTightness: -0.1258, careerNrfi: 0.5027, sample: 100 }, // Andy Fletcher
  "503502": { zoneTightness: -0.2775, careerNrfi: 0.5153, sample: 99 }, // Ryan Blakney
  "521251": { zoneTightness: 0.7337, careerNrfi: 0.4481, sample: 99 }, // Ben May
  "621660": { zoneTightness: -0.2315, careerNrfi: 0.5573, sample: 99 }, // Emil Jimenez
  "596809": { zoneTightness: 0.0508, careerNrfi: 0.4817, sample: 99 }, // Ryan Additon
  "490319": { zoneTightness: 0.0968, careerNrfi: 0.5573, sample: 99 }, // Jordan Baker
  "431232": { zoneTightness: 0.2172, careerNrfi: 0.4942, sample: 98 }, // Chad Fairchild
  "605671": { zoneTightness: 0.1576, careerNrfi: 0.5875, sample: 98 }, // Charlie Ramos
  "577468": { zoneTightness: 0.3894, careerNrfi: 0.4773, sample: 98 }, // Roberto Ortiz
  "623938": { zoneTightness: 0.1113, careerNrfi: 0.4773, sample: 98 }, // Erich Bacchus
  "482641": { zoneTightness: 0.1928, careerNrfi: 0.4728, sample: 97 }, // Adrian Johnson
  "503586": { zoneTightness: -0.0477, careerNrfi: 0.5070, sample: 97 }, // Tripp Gibson
  "484499": { zoneTightness: 0.4399, careerNrfi: 0.5412, sample: 97 }, // Manny Gonzalez
  "427243": { zoneTightness: -0.2295, careerNrfi: 0.4424, sample: 96 }, // Marvin Hudson
  "521051": { zoneTightness: -0.2160, careerNrfi: 0.4855, sample: 96 }, // Nick Mahrley
  "427366": { zoneTightness: 0.2959, careerNrfi: 0.5372, sample: 96 }, // Brian O'Nora
  "427113": { zoneTightness: -0.3440, careerNrfi: 0.5631, sample: 96 }, // Laz Diaz
  "427129": { zoneTightness: 0.1970, careerNrfi: 0.4984, sample: 95 }, // Bruce Dreckman
  "605672": { zoneTightness: -0.1903, careerNrfi: 0.5071, sample: 95 }, // Jeremie Rehak
  "608093": { zoneTightness: -0.3972, careerNrfi: 0.5291, sample: 94 }, // Junior Valentine
  "427197": { zoneTightness: 0.0423, careerNrfi: 0.5250, sample: 93 }, // Chris Guccione
  "427554": { zoneTightness: 0.0008, careerNrfi: 0.5073, sample: 93 }, // Jim Wolf
  "484183": { zoneTightness: 0.0285, careerNrfi: 0.4807, sample: 93 }, // Cory Blaser
  "427533": { zoneTightness: -0.5403, careerNrfi: 0.4804, sample: 91 }, // Mark Wegner
  "427093": { zoneTightness: -0.3995, careerNrfi: 0.5344, sample: 91 }, // Phil Cuzzi
  "504381": { zoneTightness: -0.2799, careerNrfi: 0.4533, sample: 91 }, // Will Little
  "665281": { zoneTightness: -0.2464, careerNrfi: 0.5302, sample: 90 }, // Brian Walsh
  "623945": { zoneTightness: -0.7047, careerNrfi: 0.5170, sample: 87 }, // Alex MacKay
  "427044": { zoneTightness: -0.6428, careerNrfi: 0.4983, sample: 85 }, // CB Bucknor
  "665297": { zoneTightness: -0.0326, careerNrfi: 0.4697, sample: 85 }, // Tom Hanahan
  "489985": { zoneTightness: 0.0436, careerNrfi: 0.5080, sample: 83 }, // Chad Whitson
  "658292": { zoneTightness: 0.1770, careerNrfi: 0.5081, sample: 81 }, // Derek Thomas
  "607884": { zoneTightness: -0.0010, careerNrfi: 0.4982, sample: 81 }, // Paul Clemons
  "575629": { zoneTightness: 0.6703, careerNrfi: 0.4522, sample: 78 }, // Shane Livensparger
  "427413": { zoneTightness: -0.1117, careerNrfi: 0.4672, sample: 77 }, // Tony Randazzo
  "427537": { zoneTightness: 0.4545, careerNrfi: 0.5823, sample: 75 }, // Hunter Wendelstedt
  "427128": { zoneTightness: -0.3132, careerNrfi: 0.5779, sample: 74 }, // Rob Drake
  "482608": { zoneTightness: 0.7591, careerNrfi: 0.5991, sample: 74 }, // Scott Barry
  "664263": { zoneTightness: 0.0956, careerNrfi: 0.5841, sample: 73 }, // Edwin Jimenez
  "545402": { zoneTightness: 0.3265, careerNrfi: 0.4817, sample: 72 }, // John Bacon
  "482620": { zoneTightness: -0.0930, careerNrfi: 0.4626, sample: 65 }, // Chris Conroy
  "427053": { zoneTightness: -0.1898, careerNrfi: 0.4551, sample: 62 }, // Mark Carlson
  "665576": { zoneTightness: -0.0957, careerNrfi: 0.4415, sample: 60 }, // Brock Ballou
  "427292": { zoneTightness: -0.5535, careerNrfi: 0.6124, sample: 54 }, // Ron Kulpa
  "658082": { zoneTightness: -0.4541, careerNrfi: 0.5554, sample: 49 }, // Jacob Metz
  "658536": { zoneTightness: -0.2506, careerNrfi: 0.4972, sample: 45 }, // Austin Jones
  "427286": { zoneTightness: 0.4666, careerNrfi: 0.5363, sample: 44 }, // Brian Knight
  "676581": { zoneTightness: 0.9370, careerNrfi: 0.4245, sample: 42 }, // James Jean
  "573769": { zoneTightness: -0.4175, careerNrfi: 0.5626, sample: 41 }, // Jeremy Riggs
  "427520": { zoneTightness: -0.2313, careerNrfi: 0.5478, sample: 39 }, // Larry Vanover
  "485856": { zoneTightness: -0.0311, careerNrfi: 0.5059, sample: 34 }, // Jonathan Parra
  "427362": { zoneTightness: -0.5141, careerNrfi: 0.5264, sample: 30 }, // Jeff Nelson
  "573596": { zoneTightness: 0.1143, careerNrfi: 0.4351, sample: 29 }, // Pat Hoberg
  "691042": { zoneTightness: -0.3110, careerNrfi: 0.5813, sample: 27 }, // Willie Traynor
  "427220": { zoneTightness: -0.1443, careerNrfi: 0.5723, sample: 19 }, // Angel Hernandez
  "486200": { zoneTightness: 0.1462, careerNrfi: 0.5492, sample: 17 }, // David Arrieta
  "427299": { zoneTightness: 0.1405, careerNrfi: 0.4800, sample: 14 }, // Jerry Layne
  "668921": { zoneTightness: 0.2745, careerNrfi: 0.5100, sample: 12 }, // Jen Pawol
  "658325": { zoneTightness: 0.4698, careerNrfi: 0.6038, sample: 12 }, // Tyler Jones
  "427144": { zoneTightness: 0.5826, careerNrfi: 0.3773, sample: 10 }, // Paul Emmel
  "665298": { zoneTightness: -0.2249, careerNrfi: 0.6107, sample: 10 }, // Dexter Kelley
  "676580": { zoneTightness: 0.0386, careerNrfi: 0.5283, sample: 9 }, // Steven Jaschinski
  "665299": { zoneTightness: 0.3492, careerNrfi: 0.5892, sample: 6 }, // Louie Krupa
  "664265": { zoneTightness: -0.1662, careerNrfi: 0.5328, sample: 5 }, // Jose Navas
  "665302": { zoneTightness: -0.0045, careerNrfi: 0.5145, sample: 2 }, // Dillon Wilson
  "681849": { zoneTightness: 0.1021, careerNrfi: 0.4691, sample: 2 }, // Felix Neon
  "622329": { zoneTightness: 0.0349, careerNrfi: 0.5390, sample: 1 }, // Randy Rosenberg
}
